project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - notebooks.qmd
    - notebooks/
    - thesis/
    - "!slides/**"
    # - slides/
    
website:
  title: Blood Donation Predictor
  description: "Master thesis's website about prediction of blood donations in Trieste" 
  site-url: https://erikdeluca.it/Blood-Donors
  favicon: img/logo_project.png
  navbar:
    logo: img/logo_project.png
    logo-alt: blood with some electronic circuit, like a mother board red and white
    left:
      - href: index.qmd
        text: Home
      - href: thesis/index.html
        text: Thesis
      - href: notebooks.qmd
        text: Notebooks
      - href: slides\\presentation.html
        text: Slides
      - href: dashboard.qmd
        text: Dashboard
  page-footer:
    background: light # or `dark`
    left: |
      DE LUCA ERIK, P.IVA: IT01401250327 <br>
      Sede legale: Via dei Giardini, 50 - 34146 - Trieste
    center: |
      Copyright 2025, Erik De Luca 
    right: |
      This website is built with {{< fa heart title="a heart" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://github.com/erikdeluca/erikdeluca.github.io){target=_blank}, and [Quarto](https://quarto.org/){target=_blank}
  cookie-consent:
    type: express
    # style: headline
    palette: light
    # storage: cookies
  google-analytics:
    tracking-id: G-X7MSMF2M7M
    anonymize-ip: true
  # for sharing links  of my website
  open-graph: true

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    fig-format: png # to get transparent background and applying bg color's theme
    # mainfont: figtree
    # titlefont: parkinsans
    # light: minty
    # dark: solar
    toc: true
    page-layout: full
    code-fold: true
    df-print: paged
    warnings: false

execute:
  freeze: auto
