name: blood-donors
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  # --- PYTHON CORE & TOOLS ---
  - python=3.11
  - pip
  - jupyterlab
  - ipykernel
  - flake8
  - pytest
  - pre-commit
  - ruff                # Fast Python linter/formatter
  - pyprojroot
  - python-dotenv

  # for Github Action
  # - protobuf=3.20.3
  # - altair<5
  # - streamlit<1.25

  # --- PYTHON LIBRARIES ---
  - streamlit=1.53.0
  - plotly
  - pandas
  - numpy
  - scipy
  - statsmodels
  - matplotlib
  - seaborn
  - pytorch
  - pyro-ppl           # Probabilistic programming (HMM models)
  - torchvision
  - tabulate
  - plotnine
  - polars
  - scikit-learn # for confusion matrix

  # --- SYSTEM LIBS ---
  - libopenblas
  - pkg-config

  # --- R CORE & UTILS ---
  - r-base
  - r-tidyverse        # Core R data science ecosystem
  - r-pacman           # Package management utility
  - r-renv             # Local environment management
  - r-reticulate       # Python-R interface
  - r-conflicted       # Manage function name conflicts
  - r-here             # Project-relative file paths
  - r-janitor          # Data cleaning and tabulations
  - r-readxl           # Excel file reader
  - r-pacman

  # --- R DOCUMENTATION & FONTS ---
  - r-rmarkdown
  - r-knitr
  - r-quarto
  - r-gdtools          # Tools for graphical rendering
  - r-gfonts           # Google fonts offline support
  - r-systemfonts      # Native system font access

  # --- R VISUALIZATION ---
  - r-patchwork        # Combine multiple plots
  - r-scales           # Map data to aesthetics
  - r-hexbin           # Hexagonal binning plots
  - r-dotwhisker       # Dot-and-whisker regression plots

  # --- Lifecontingencies ---
  - r-igraph
  # - r-markovchain
  - r-expm
  - r-rcppparallel

  # --- R STATS & MODELING ---
  - r-tidymodels       # Unified modeling framework
  - r-broom.mixed      # Tidying mixed models
  - r-broom.helpers    # Model summary helpers
  - r-gt               # Presentation-ready tables
  - r-gtsummary        # Publication-quality summary tables
  - r-glmmtmb          # Generalized linear mixed models
  - r-glmnet           # Lasso and Elastic-Net regression
  - r-poissonreg       # Poisson regression wrappers
  - r-statmod          # Statistical modeling tools
  - r-mass             # Applied statistics functions
  # - r-lifecontingencies # Financial and actuarial mathematics
  - r-doparallel       # Parallel backend for foreach
  # - r-envalysis        # Environmental data analysis tools

# --- AI AGENTS ---
  - google-genai
