project:
  type: default
  output-dir: ../docs/slides
  render:
    - presentation.qmd

format:
  revealjs:
    theme:
      - simple
      - styles_revealjs.scss   # faster with CSS version -> styles_revealjs.css
    code-block-height: 500px
    smaller: true
    slide-number: c
    output-location: fragment
    preview-links: auto
    fig-dpi: 300
    fig-align: center
    lang: en
    chalkboard: true

execute:
  freeze: auto
  warning: false
  message: false