# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

from shiny import reactive
from shiny.express import ui, input, render
from pyprojroot import here
import pandas as pd
import polars as pl
import numpy as np
import plotnine as pn
import torch
import re


# ---------------------------------------------------------------------
# Moduli progetto
# ---------------------------------------------------------------------

import hmm_glm_model as hmm_glm
import hmm_glm_plots as hmm_pl
import hmm_glm_viterbi as viterbi
import hmm_glm_prediction as hmm_pred

# ---------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------
DATA_PATH = "recent_donations.csv"
MODEL_PATH = "hmm_glm_full.pt"
COVID_YEARS = (2020, 2021, 2022)

# ---------------------------------------------------------------------
# Dati e covariate
# ---------------------------------------------------------------------
data_pd = pd.read_csv(DATA_PATH)
df = pl.from_pandas(data_pd)
BIRTH_YEAR_MEAN = df["birth_year"].mean()
BIRTH_YEAR_STD = df["birth_year"].std()

year_cols = sorted([c for c in df.columns if c.startswith("y_")])
T = len(year_cols)
years_num = np.array([int(c[2:]) for c in year_cols])  # es. [2009,..,2023]

# Osservazioni (N,T)
obs = (
    df.select(year_cols)
      .fill_null(0)
      .to_numpy()
      .astype(int)
)
N = obs.shape[0]

# Covariate iniziali (pi): [intercetta, birth_year_norm, gender_code]
df = df.with_columns([
    (pl.col("gender") == "F").cast(pl.Int8).alias("gender_code"),
    ((pl.col("birth_year") - pl.col("birth_year").mean()) / pl.col("birth_year").std()).alias("birth_year_norm"),
])
birth_year_norm = df["birth_year_norm"].to_numpy()
gender_code     = df["gender_code"].to_numpy()
intercept_vec   = np.ones_like(birth_year_norm)
cov_init = np.stack([intercept_vec, birth_year_norm, gender_code], axis=1)  # (N,3)

# Covariate transizioni (A): [intercetta, 6 dummies età, covid]
ages = years_num[None, :] - df["birth_year"].to_numpy()[:, None]           # (N,T)
covid_mask = np.isin(years_num, list(COVID_YEARS)).astype(float)           # (T,)
covid_years = np.tile(covid_mask, (N, 1))                                  # (N,T)

age_bins = np.array([18, 25, 35, 45, 55, 60, 65, 75])  # 7 classi → 6 dummies (saltiamo baseline)
ages_binned = np.digitize(ages, age_bins, right=False)  # 1..7
n_agebins = len(age_bins) - 1
ages_binned = np.clip(ages_binned, 1, n_agebins)
ages_onehot = np.eye(n_agebins)[ages_binned - 1][:, :, 1:]  # drop baseline 18–24

intercept_tile = np.ones((N, T, 1))
cov_tran = np.concatenate([intercept_tile, ages_onehot, covid_years[:, :, None]], axis=2)  # (N,T,8)

# Covariate emissioni (GLM per stato): [intercetta, gender, 6 dummies età, covid] → (N,T,9)
gender_code_tile = np.repeat(gender_code[:, None], T, axis=1)
cov_emission = np.concatenate(
    [intercept_tile, gender_code_tile[:, :, None], ages_onehot, covid_years[:, :, None]],
    axis=2
)

# Torch tensors
obs_torch       = torch.tensor(obs,          dtype=torch.long)
cov_init_torch  = torch.tensor(cov_init,     dtype=torch.float32)
cov_tran_torch  = torch.tensor(cov_tran,     dtype=torch.float32)
cov_emiss_torch = torch.tensor(cov_emission, dtype=torch.float32)

# Registro donatori per UI
UIDS = data_pd["unique_number"].astype(str).tolist()
UID_TO_IDX = {uid: i for i, uid in enumerate(UIDS)}

choices_map = {
    f'{int(r["unique_number"])} - {r["gender"]} ({int(r["birth_year"])})': str(r["unique_number"])
    for _, r in data_pd.iterrows()
}
DEFAULT_UID = UIDS[0]

choices_map = df["unique_number"].to_list()

# ---------------------------------------------------------------------
# Carica parametri e percorsi Viterbi
# ---------------------------------------------------------------------
W_pi, W_A, pi_base, A_base, beta_em = hmm_glm.load_hmm_params(MODEL_PATH)
PATHS_ALL = viterbi.viterbi_paths_glm(
    obs_torch,
    cov_init_torch,
    cov_tran_torch,
    cov_emiss_torch,
    MODEL_PATH
)  # torch.LongTensor (N,T)

# ---------------------------------------------------------------------
# Previsione semplice (stato ultimo, covariate dell'ultimo anno)
# ---------------------------------------------------------------------
def simple_predict_for_idx(i: int):
    # usa lo stato latente ultimo e le covariate di emissione all'ultimo anno
    z_last = int(PATHS_ALL[i, -1])
    x_em_last = cov_emiss_torch[i, -1, :].cpu().numpy()  # proxy per T+1
    beta_k = beta_em[z_last, :]
    log_mu = float((x_em_last * beta_k).sum())
    mu = float(np.exp(log_mu))
    prob_donate = float(1.0 - np.exp(-mu))  # P(y>0) per Poisson
    return {
        "last_state": z_last,
        "expected_next": mu,
        "prob_donate_next": prob_donate,
    }

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    ui.input_numeric("birth_year", "Anno di nascita", 1985, min=1955, max=2010, step=1)
    ui.input_radio_buttons("gender", "Genere", choices=["M", "F"], selected="M", inline=True)
    ui.input_numeric("start_year", "Anno inizio", 2019, min=1970, max=2023, step=1)
    # ui.input_numeric("end_year", "Anno fine", 2023, min=2009, max=2030, step=1)
    ui.input_text_area("counts_csv", "Conteggi annuali",
     placeholder="0,1,0,0,1, ...", value="0,0,1,2,1")

    def parse_counts(text):
        return [int(float(x)) for x in text.replace(",", " ").split() if x.strip()] if text.strip() else []

    # ========================================================================

    @reactive.calc
    def prediction_result():
        birth_year = int(input.birth_year())
        gender = input.gender()
        start_year = int(input.start_year())
        donations = parse_counts(input.counts_csv())
        years = list(range(start_year, start_year + len(donations)))
        if len(donations) < 1:
            return None
        result = hmm_pred.predict_donor(
            birth_year=birth_year,
            gender=gender,
            history_years=years,
            history_counts=donations,
            birth_year_mean=BIRTH_YEAR_MEAN,
            birth_year_std=BIRTH_YEAR_STD,
            model_path=MODEL_PATH,
        )
        return result

    # ========================================================================

    @render.plot
    def plot_pmf_next():
        res = prediction_result()
        if not res:
            return (
                pn.ggplot(pd.DataFrame({'x': [], 'y': []}), pn.aes('x', 'y')) +
                pn.labs(title="Inserisci dati per vedere la distribuzione")
            )

        # Converte il dict pmf in dataframe ordinato
        pmf = res['pmf_next']
        cats = [k for k in pmf.keys()]  # mantiene l'ordine
        probs = [pmf[k] for k in cats]
        df_pmf = pd.DataFrame({'n_donations': cats, 'probability': probs})

        p = (
            pn.ggplot(df_pmf, pn.aes(x='n_donations', y='probability'))
            + pn.geom_col(fill="#86ba90")
            + pn.geom_text(
                pn.aes(label='probability'),
                format_string="{:.1%}",
                va='bottom',
                nudge_y=0.01,
                size=10
            )
            + pn.scale_y_continuous(labels=lambda l: [f"{v*100:.0f}%" for v in l], limits=(0, max(probs)*1.25))
            + pn.labs(
                title="Probabilità delle donazioni future",
                x="Numero di future donazioni (prossimo anno)",
                y="Probabilità (%)"
            )
            + pn.annotate(
                "text",
                x=len(df_pmf)-0.5,
                y=max(probs)*1.1,
                label=f"E[y] = {res['expected_next']:.2f}\nP(≥1) = {res['prob_donate_next']:.2%}",
                ha="right",
                size=10
            )
            + pn.theme_minimal()
        )
        return p

    # ========================================================================

    @render.plot
    def plot():
        res = prediction_result()
        if not res:
            return hmm_pl.plot_donor_simple(
                years=[],
                donations=[],
                title="Inserisci i dati al lato per simulare."
            )
        return hmm_pl.plot_donor_simple(
            years=res["years"],
            donations=res["counts"],
            states=res["viterbi_states"],
            expected_next=res["expected_next"],
            next_year=res["next_year"],
            title=f"Simulazione {input.gender()} {input.birth_year()}",
            y_max=4,
            show_legend=True
        )

    # ========================================================================

    ui.input_select(
        "donor_uid", "Donatore",
        choices=choices_map,
        selected=DEFAULT_UID,
        width="100%"
    )

    # ========================================================================

    @render.ui
    def vb_last_state():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0) 
        last_state = int(PATHS_ALL[i, -1])
        return ui.value_box(
            title="Stato latente (ultimo)",
            value=str(last_state)
        )

    # ========================================================================

    @render.ui
    def vb_prob_next():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0) 
        p = simple_predict_for_idx(i)
        prob_next = p.get("prob_donate_next", None)
        val_txt = f"{prob_next:.3f}" if prob_next is not None else "NA"
        return ui.value_box(
            title="P(donare next)",
            value=val_txt
        )

    # ========================================================================

    @render.ui
    def vb_expected_next():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0) 
        p = simple_predict_for_idx(i)
        mu_next = p.get("expected_next", None)
        val_txt = f"{mu_next:.3f}" if mu_next is not None else "NA"
        return ui.value_box(
            title="E[y next]",
            value=val_txt
        )

    # ========================================================================

    @render.plot
    def plot_new_donor():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0)

        years_hist = years_num.tolist()
        p = simple_predict_for_idx(i)

        g = hmm_pl.plot_donor_gg(
            idx=i,
            obs_torch=obs_torch,
            paths=PATHS_ALL,
            years=years_hist,
            expected_next=p["expected_next"],
            y_true_next=obs[i,-1],
            next_year=int(years_hist[-1] + 1),
            y_max=4
        )
        return g

    # ========================================================================



    return None


_static_assets = ["dashboard_files","app\\dashboard_files\\libs\\quarto-html\\tippy.css","app\\dashboard_files\\libs\\quarto-html\\quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css","app\\dashboard_files\\libs\\quarto-html\\quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css","app\\dashboard_files\\libs\\bootstrap\\bootstrap-icons.css","app\\dashboard_files\\libs\\bootstrap\\bootstrap-366232e161007004ec4c38bee3e806d4.min.css","app\\dashboard_files\\libs\\bootstrap\\bootstrap-dark-366232e161007004ec4c38bee3e806d4.min.css","app\\dashboard_files\\libs\\clipboard\\clipboard.min.js","app\\dashboard_files\\libs\\quarto-html\\quarto.js","app\\dashboard_files\\libs\\quarto-html\\tabsets\\tabsets.js","app\\dashboard_files\\libs\\quarto-html\\popper.min.js","app\\dashboard_files\\libs\\quarto-html\\tippy.umd.min.js","app\\dashboard_files\\libs\\quarto-html\\anchor.min.js","app\\dashboard_files\\libs\\bootstrap\\bootstrap.min.js","app\\dashboard_files\\libs\\quarto-dashboard\\quarto-dashboard.js","app\\dashboard_files\\libs\\quarto-dashboard\\stickythead.js","app\\dashboard_files\\libs\\quarto-dashboard\\web-components.js","app\\dashboard_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "dashboard.html",
    server,
    static_assets=_static_assets,
)
