# This file generated by Quarto; do not edit by hand.
# shiny_mode: core

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui

from shiny import reactive
from shiny.express import ui, input, render
from pyprojroot import here
import pandas as pd
import polars as pl
import numpy as np
import torch
import sys
import re

# ---------------------------------------------------------------------
# Moduli progetto
# ---------------------------------------------------------------------
python_dir = str(here("python"))
if python_dir not in sys.path:
    sys.path.insert(0, python_dir)

import hmm_glm_model as hmm_glm
import hmm_glm_plots as hmm_pl
import hmm_glm_viterbi as viterbi

# ---------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------
DATA_PATH = here("data/recent_donations.csv")
MODEL_PATH = here("models/hmm_glm_full.pt")
COVID_YEARS = (2020, 2021, 2022)

# ---------------------------------------------------------------------
# Dati e covariate
# ---------------------------------------------------------------------
data_pd = pd.read_csv(DATA_PATH)
df = pl.from_pandas(data_pd)

year_cols = sorted([c for c in df.columns if c.startswith("y_")])
T = len(year_cols)
years_num = np.array([int(c[2:]) for c in year_cols])  # es. [2009,..,2023]

# Osservazioni (N,T)
obs = (
    df.select(year_cols)
      .fill_null(0)
      .to_numpy()
      .astype(int)
)
N = obs.shape[0]

# Covariate iniziali (pi): [intercetta, birth_year_norm, gender_code]
df = df.with_columns([
    (pl.col("gender") == "F").cast(pl.Int8).alias("gender_code"),
    ((pl.col("birth_year") - pl.col("birth_year").mean()) / pl.col("birth_year").std()).alias("birth_year_norm"),
])
birth_year_norm = df["birth_year_norm"].to_numpy()
gender_code     = df["gender_code"].to_numpy()
intercept_vec   = np.ones_like(birth_year_norm)
cov_init = np.stack([intercept_vec, birth_year_norm, gender_code], axis=1)  # (N,3)

# Covariate transizioni (A): [intercetta, 6 dummies età, covid]
ages = years_num[None, :] - df["birth_year"].to_numpy()[:, None]           # (N,T)
covid_mask = np.isin(years_num, list(COVID_YEARS)).astype(float)           # (T,)
covid_years = np.tile(covid_mask, (N, 1))                                  # (N,T)

age_bins = np.array([18, 25, 35, 45, 55, 60, 65, 75])  # 7 classi → 6 dummies (saltiamo baseline)
ages_binned = np.digitize(ages, age_bins, right=False)  # 1..7
n_agebins = len(age_bins) - 1
ages_binned = np.clip(ages_binned, 1, n_agebins)
ages_onehot = np.eye(n_agebins)[ages_binned - 1][:, :, 1:]  # drop baseline 18–24

intercept_tile = np.ones((N, T, 1))
cov_tran = np.concatenate([intercept_tile, ages_onehot, covid_years[:, :, None]], axis=2)  # (N,T,8)

# Covariate emissioni (GLM per stato): [intercetta, gender, 6 dummies età, covid] → (N,T,9)
gender_code_tile = np.repeat(gender_code[:, None], T, axis=1)
cov_emission = np.concatenate(
    [intercept_tile, gender_code_tile[:, :, None], ages_onehot, covid_years[:, :, None]],
    axis=2
)

# Torch tensors
obs_torch       = torch.tensor(obs,          dtype=torch.long)
cov_init_torch  = torch.tensor(cov_init,     dtype=torch.float32)
cov_tran_torch  = torch.tensor(cov_tran,     dtype=torch.float32)
cov_emiss_torch = torch.tensor(cov_emission, dtype=torch.float32)

# Registro donatori per UI
UIDS = data_pd["unique_number"].astype(str).tolist()
UID_TO_IDX = {uid: i for i, uid in enumerate(UIDS)}

choices_map = {
    f'{int(r["unique_number"])} - {r["gender"]} ({int(r["birth_year"])})': str(r["unique_number"])
    for _, r in data_pd.iterrows()
}
DEFAULT_UID = UIDS[0]

choices_map = df["unique_number"].to_list()

# ---------------------------------------------------------------------
# Carica parametri e percorsi Viterbi
# ---------------------------------------------------------------------
W_pi, W_A, pi_base, A_base, beta_em = hmm_glm.load_hmm_params(MODEL_PATH)
PATHS_ALL = viterbi.viterbi_paths_glm(
    obs_torch,
    cov_init_torch,
    cov_tran_torch,
    cov_emiss_torch,
    MODEL_PATH
)  # torch.LongTensor (N,T)

# ---------------------------------------------------------------------
# Previsione semplice (stato ultimo, covariate dell'ultimo anno)
# ---------------------------------------------------------------------
def simple_predict_for_idx(i: int):
    # usa lo stato latente ultimo e le covariate di emissione all'ultimo anno
    z_last = int(PATHS_ALL[i, -1])
    x_em_last = cov_emiss_torch[i, -1, :].cpu().numpy()  # proxy per T+1
    beta_k = beta_em[z_last, :]
    log_mu = float((x_em_last * beta_k).sum())
    mu = float(np.exp(log_mu))
    prob_donate = float(1.0 - np.exp(-mu))  # P(y>0) per Poisson
    return {
        "last_state": z_last,
        "expected_next": mu,
        "prob_donate_next": prob_donate,
    }

# ========================================================================




def server(input: Inputs, output: Outputs, session: Session) -> None:
    ui.input_select(
        "donor_uid", "Donatore",
        choices=choices_map,
        selected=DEFAULT_UID,
        width="100%"
    )
    # ui.input_action_button("next", "Prossimo donatore", class_="btn-primary")   

    # @reactive.effect
    # def _go_next_donor():
    #     session = get_current_session()
    #     session.input["next"]()  # crea la dipendenza dall'evento "next"

    #     uid = session.input["donor_uid"]()     # UID corrente (str)
    #     i = UID_TO_IDX.get(str(uid), 0)
    #     new_i = (i + 1) % len(UIDS)

    #     ui.update_select("donor_uid", selected=UIDS[new_i], session=session)

    # ========================================================================

    # ui.input_select("dist", "Distribution:", choices=["kde", "hist"])
    # ui.input_checkbox("rug", "Show rug marks", value = False)

    # ========================================================================

    @render.ui
    def vb_last_state():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0) 
        last_state = int(PATHS_ALL[i, -1])
        return ui.value_box(
            title="Stato latente (ultimo)",
            value=str(last_state)
        )

    @render.ui
    def vb_prob_next():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0) 
        p = simple_predict_for_idx(i)
        prob_next = p.get("prob_donate_next", None)
        val_txt = f"{prob_next:.3f}" if prob_next is not None else "NA"
        return ui.value_box(
            title="P(donare next)",
            value=val_txt
        )

    @render.ui
    def vb_expected_next():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0) 
        p = simple_predict_for_idx(i)
        mu_next = p.get("expected_next", None)
        val_txt = f"{mu_next:.3f}" if mu_next is not None else "NA"
        return ui.value_box(
            title="E[y next]",
            value=val_txt
        )

    # ========================================================================

    @render.plot
    def plot():
        uid = input.donor_uid()
        i = UID_TO_IDX.get(uid, 0)

        years_hist = years_num.tolist()
        p = simple_predict_for_idx(i)

        g = hmm_pl.plot_donor_gg(
            idx=i,
            obs_torch=obs_torch,
            paths=PATHS_ALL,
            years=years_hist,
            expected_next=p["expected_next"],
            y_true_next=obs[i,-1],
            next_year=int(years_hist[-1] + 1),
            y_max=4
        )
        return g

    # ========================================================================

    ui.input_numeric("birth_year", "Anno di nascita", 1985, min=1955, max=2010, step=1)
    ui.input_radio_buttons("gender", "Genere", choices=["M", "F"], selected="M", inline=True)
    ui.input_numeric("start_year", "Anno inizio", 2009, min=1970, max=2023, step=1)
    ui.input_numeric("end_year", "Anno fine", 2023, min=2009, max=2030, step=1)
    ui.input_text_area("counts_csv", "Conteggi annuali (CSV o spazi)", placeholder="0,1,0,0,1, ...")
    ui.input_action_button("simulate", "Simula", class_="btn-success")

    # ========================================================================



    return None


_static_assets = ["dashboard_files","app\\dashboard_files\\libs\\quarto-html\\tippy.css","app\\dashboard_files\\libs\\quarto-html\\quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css","app\\dashboard_files\\libs\\quarto-html\\quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css","app\\dashboard_files\\libs\\bootstrap\\bootstrap-icons.css","app\\dashboard_files\\libs\\bootstrap\\bootstrap-366232e161007004ec4c38bee3e806d4.min.css","app\\dashboard_files\\libs\\bootstrap\\bootstrap-dark-366232e161007004ec4c38bee3e806d4.min.css","app\\dashboard_files\\libs\\clipboard\\clipboard.min.js","app\\dashboard_files\\libs\\quarto-html\\quarto.js","app\\dashboard_files\\libs\\quarto-html\\tabsets\\tabsets.js","app\\dashboard_files\\libs\\quarto-html\\popper.min.js","app\\dashboard_files\\libs\\quarto-html\\tippy.umd.min.js","app\\dashboard_files\\libs\\quarto-html\\anchor.min.js","app\\dashboard_files\\libs\\bootstrap\\bootstrap.min.js","app\\dashboard_files\\libs\\quarto-dashboard\\quarto-dashboard.js","app\\dashboard_files\\libs\\quarto-dashboard\\stickythead.js","app\\dashboard_files\\libs\\quarto-dashboard\\web-components.js","app\\dashboard_files\\libs\\quarto-dashboard\\components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "dashboard.html",
    server,
    static_assets=_static_assets,
)
