project:
  type: book
  output-dir: ../docs/thesis/

book:
  title: |
    Modellazione statistica delle donazioni di sangue nella provincia di Trieste
  subtitle: |
    Modelli markoviani a stati nascosti integrati da modelli lineari generalizzati con un approccio bayesiano
  site-url: https://erikdeluca.it/Blood-Donors/thesis
  favicon: img/logo_project.png
  cover-image: img/logo_project.png
  repo-url: https://github.com/erikdeluca/Blood-Donors
  repo-actions: [source, issue]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]
  page-navigation: true
  reader-mode: true
  navbar:
    title: false
    logo: img/logo_project.png
    logo-alt: blood with some electronic circuit, like a mother board red and white
    left:
      - href: ../index.html
        text: Home
      - href: index.html
        text: Thesis
      - href: ../notebooks.html
        text: Notebooks
      - href: ../slides/presentation.html
        text: Slides
        target: _blank
      - href: ../dashboard.html
        text: Dashboard
  author:
    - name: "Erik De Luca"
      email: "erik.deluca@studenti.units.it"
      url: erikdeluca.it
      affiliations:
        - name: "Università degli Studi di Trieste"
          city: "Trieste"
          state: "Italia"
          url: www.units.it
    # - name: Leonardo Egidi
    #   roles: supervision
    #   degrees: Prof.
    #   affiliations:
    #     - name: "Università degli Studi di Trieste"
    #       city: "Trieste"
    #       state: "Italia"
    #       url: www.units.it
  license: "CC BY-NC"
  date: 30/09/2025
  chapters:
    - index.qmd
    - introduzione.qmd
    - glm.qmd
    - hmm.qmd
    - dashboard.qmd
    - conclusioni.qmd
    - references.qmd
  output-file: "master_thesis"
  open-graph: true

lang: it
bibliography: bibliography.bib
fig-cap-location: bottom

format:
  html:
    theme: 
      - cosmo
      - ../styles.scss
    df-print: paged
    toc-depth: 3
    number-depth: 2
    math: mathjax
    warnings: false
  pdf:
    filters: [remove_title.lua]
    documentclass: scrbook
    classoption:
      - a4paper
      - twoside
      - open=right
      - 12pt
    papersize: a4
    geometry: top=3cm,bottom=3cm,left=3cm,right=3cm
    pdf-engine: pdflatex
    keep-tex: true
    template-partials:
      - partials/title.tex          # vuoto: sopprime la titlepage standard
    include-in-header:
      # - text: |
      #       \addtokomafont{disposition}{\rmfamily}      documentclass: scrreprt
      - preamble.tex
    include-before-body:
      - partials/frontespizio.tex
    lof: true                  # List of Figures
    lot: true                  # List of Tables
    colorlinks: true
    toc: true
    toc-depth: 3 
    number-depth: 2
    output-dir: 
      - ../docs/thesis/
      - ./
  epub:
    toc-depth: 3 
    number-depth: 2
    cover-image: ../img/logo_project.png

pdf:
  cite-method: natbib
  biblio-style: plain

metadata:
  supervisor:
    role: "Relatore"
    name: "Prof. Leonardo Egidi"
  author:
    name: Erik De Luca

execute:
  echo: false
  warning: false
  error: false

copyright: 
  holder: Erik De Luca
  year: 2025