name: Quarto Publish

on:
  workflow_dispatch:
  push:
    branches: master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    # Conda shell
    defaults:
      run:
        shell: bash -l {0}

    # disable R profile to avoid conflicts
    env:
      R_PROFILE_USER: "/dev/null"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: blood-donors
          environment-file: environment.yml
          auto-activate-base: false
          use-mamba: true

      - name: Configure Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Publish to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript -e ".libPaths()"

          quarto publish gh-pages
